; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=mips -mcpu=mips2 -relocation-model=pic \
; RUN:   -mips-jalr-reloc=false | FileCheck %s -check-prefixes=MIPS2
; RUN: llc < %s -mtriple=mips -mcpu=mips32 -relocation-model=pic \
; RUN:   -mips-jalr-reloc=false | FileCheck %s -check-prefixes=MIPS32

; RUN: llc < %s -mtriple=mips64 -mcpu=mips3 -relocation-model=pic \
; RUN:   -mips-jalr-reloc=false | FileCheck %s -check-prefixes=MIPS3
; RUN: llc < %s -mtriple=mips64 -mcpu=mips64 -relocation-model=pic \
; RUN:   -mips-jalr-reloc=false | FileCheck %s -check-prefixes=MIPS64

; RUN: llc < %s -mtriple=mips -mcpu=mips2 -O0 -relocation-model=pic \
; RUN:   -mips-jalr-reloc=false | FileCheck %s -check-prefixes=MIPS2-O0
; RUN: llc < %s -mtriple=mips -mcpu=mips32 -O0 -relocation-model=pic \
; RUN:   -mips-jalr-reloc=false | FileCheck %s -check-prefixes=MIPS32-O0

define signext i32 @srem_i32(i32 signext %a, i32 signext %b, i32 signext %c) {
; MIPS2-LABEL: srem_i32:
; MIPS2:       # %bb.0: # %entry
; MIPS2-NEXT:    div $zero, $4, $5
; MIPS2-NEXT:    teq $5, $zero, 7
; MIPS2-NEXT:    mfhi $1
; MIPS2-NEXT:    nop
; MIPS2-NEXT:    nop
; MIPS2-NEXT:    div $zero, $1, $6
; MIPS2-NEXT:    teq $6, $zero, 7
; MIPS2-NEXT:    mfhi $2
; MIPS2-NEXT:    jr $ra
; MIPS2-NEXT:    nop
;
; MIPS32-LABEL: srem_i32:
; MIPS32:       # %bb.0: # %entry
; MIPS32-NEXT:    div $zero, $4, $5
; MIPS32-NEXT:    teq $5, $zero, 7
; MIPS32-NEXT:    mfhi $1
; MIPS32-NEXT:    div $zero, $1, $6
; MIPS32-NEXT:    teq $6, $zero, 7
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    mfhi $2
;
; MIPS3-LABEL: srem_i32:
; MIPS3:       # %bb.0: # %entry
; MIPS3-NEXT:    div $zero, $4, $5
; MIPS3-NEXT:    teq $5, $zero, 7
; MIPS3-NEXT:    mfhi $1
; MIPS3-NEXT:    nop
; MIPS3-NEXT:    nop
; MIPS3-NEXT:    div $zero, $1, $6
; MIPS3-NEXT:    teq $6, $zero, 7
; MIPS3-NEXT:    mfhi $2
; MIPS3-NEXT:    jr $ra
; MIPS3-NEXT:    nop
;
; MIPS64-LABEL: srem_i32:
; MIPS64:       # %bb.0: # %entry
; MIPS64-NEXT:    div $zero, $4, $5
; MIPS64-NEXT:    teq $5, $zero, 7
; MIPS64-NEXT:    mfhi $1
; MIPS64-NEXT:    div $zero, $1, $6
; MIPS64-NEXT:    teq $6, $zero, 7
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    mfhi $2
;
; MIPS2-O0-LABEL: srem_i32:
; MIPS2-O0:       # %bb.0: # %entry
; MIPS2-O0-NEXT:    div $zero, $4, $5
; MIPS2-O0-NEXT:    teq $5, $zero, 7
; MIPS2-O0-NEXT:    mfhi $1
; MIPS2-O0-NEXT:    nop
; MIPS2-O0-NEXT:    nop
; MIPS2-O0-NEXT:    div $zero, $1, $6
; MIPS2-O0-NEXT:    teq $6, $zero, 7
; MIPS2-O0-NEXT:    mfhi $2
; MIPS2-O0-NEXT:    jr $ra
; MIPS2-O0-NEXT:    nop
;
; MIPS32-O0-LABEL: srem_i32:
; MIPS32-O0:       # %bb.0: # %entry
; MIPS32-O0-NEXT:    div $zero, $4, $5
; MIPS32-O0-NEXT:    teq $5, $zero, 7
; MIPS32-O0-NEXT:    mfhi $1
; MIPS32-O0-NEXT:    div $zero, $1, $6
; MIPS32-O0-NEXT:    teq $6, $zero, 7
; MIPS32-O0-NEXT:    mfhi $2
; MIPS32-O0-NEXT:    jr $ra
; MIPS32-O0-NEXT:    nop
entry:
  %rem = srem i32 %a, %b
  %rem1 = srem i32 %rem, %c
  ret i32 %rem1
}

define signext i64 @srem_i64(i64 signext %a, i64 signext %b, i64 signext %c) {
; MIPS2-LABEL: srem_i64:
; MIPS2:       # %bb.0: # %entry
; MIPS2-NEXT:    lui $2, %hi(_gp_disp)
; MIPS2-NEXT:    addiu $2, $2, %lo(_gp_disp)
; MIPS2-NEXT:    addiu $sp, $sp, -24
; MIPS2-NEXT:    .cfi_def_cfa_offset 24
; MIPS2-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; MIPS2-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; MIPS2-NEXT:    .cfi_offset 31, -4
; MIPS2-NEXT:    .cfi_offset 16, -8
; MIPS2-NEXT:    addu $16, $2, $25
; MIPS2-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS2-NEXT:    jalr $25
; MIPS2-NEXT:    move $gp, $16
; MIPS2-NEXT:    move $4, $2
; MIPS2-NEXT:    lw $6, 40($sp)
; MIPS2-NEXT:    lw $7, 44($sp)
; MIPS2-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS2-NEXT:    jalr $25
; MIPS2-NEXT:    move $5, $3
; MIPS2-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; MIPS2-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; MIPS2-NEXT:    jr $ra
; MIPS2-NEXT:    addiu $sp, $sp, 24
;
; MIPS32-LABEL: srem_i64:
; MIPS32:       # %bb.0: # %entry
; MIPS32-NEXT:    lui $2, %hi(_gp_disp)
; MIPS32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; MIPS32-NEXT:    addiu $sp, $sp, -24
; MIPS32-NEXT:    .cfi_def_cfa_offset 24
; MIPS32-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; MIPS32-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; MIPS32-NEXT:    .cfi_offset 31, -4
; MIPS32-NEXT:    .cfi_offset 16, -8
; MIPS32-NEXT:    addu $16, $2, $25
; MIPS32-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS32-NEXT:    jalr $25
; MIPS32-NEXT:    move $gp, $16
; MIPS32-NEXT:    move $4, $2
; MIPS32-NEXT:    lw $6, 40($sp)
; MIPS32-NEXT:    lw $7, 44($sp)
; MIPS32-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS32-NEXT:    jalr $25
; MIPS32-NEXT:    move $5, $3
; MIPS32-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; MIPS32-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    addiu $sp, $sp, 24
;
; MIPS3-LABEL: srem_i64:
; MIPS3:       # %bb.0: # %entry
; MIPS3-NEXT:    ddiv $zero, $4, $5
; MIPS3-NEXT:    teq $5, $zero, 7
; MIPS3-NEXT:    mfhi $1
; MIPS3-NEXT:    nop
; MIPS3-NEXT:    nop
; MIPS3-NEXT:    ddiv $zero, $1, $6
; MIPS3-NEXT:    teq $6, $zero, 7
; MIPS3-NEXT:    mfhi $2
; MIPS3-NEXT:    jr $ra
; MIPS3-NEXT:    nop
;
; MIPS64-LABEL: srem_i64:
; MIPS64:       # %bb.0: # %entry
; MIPS64-NEXT:    ddiv $zero, $4, $5
; MIPS64-NEXT:    teq $5, $zero, 7
; MIPS64-NEXT:    mfhi $1
; MIPS64-NEXT:    ddiv $zero, $1, $6
; MIPS64-NEXT:    teq $6, $zero, 7
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    mfhi $2
;
; MIPS2-O0-LABEL: srem_i64:
; MIPS2-O0:       # %bb.0: # %entry
; MIPS2-O0-NEXT:    lui $2, %hi(_gp_disp)
; MIPS2-O0-NEXT:    addiu $2, $2, %lo(_gp_disp)
; MIPS2-O0-NEXT:    addiu $sp, $sp, -32
; MIPS2-O0-NEXT:    .cfi_def_cfa_offset 32
; MIPS2-O0-NEXT:    sw $ra, 28($sp) # 4-byte Folded Spill
; MIPS2-O0-NEXT:    sw $18, 24($sp) # 4-byte Folded Spill
; MIPS2-O0-NEXT:    sw $17, 20($sp) # 4-byte Folded Spill
; MIPS2-O0-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; MIPS2-O0-NEXT:    .cfi_offset 31, -4
; MIPS2-O0-NEXT:    .cfi_offset 18, -8
; MIPS2-O0-NEXT:    .cfi_offset 17, -12
; MIPS2-O0-NEXT:    .cfi_offset 16, -16
; MIPS2-O0-NEXT:    addu $16, $2, $25
; MIPS2-O0-NEXT:    lw $17, 52($sp)
; MIPS2-O0-NEXT:    lw $18, 48($sp)
; MIPS2-O0-NEXT:    # kill: def $at killed $a3
; MIPS2-O0-NEXT:    # kill: def $at killed $a2
; MIPS2-O0-NEXT:    # kill: def $at killed $a1
; MIPS2-O0-NEXT:    # kill: def $at killed $a0
; MIPS2-O0-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS2-O0-NEXT:    move $gp, $16
; MIPS2-O0-NEXT:    jalr $25
; MIPS2-O0-NEXT:    nop
; MIPS2-O0-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS2-O0-NEXT:    move $4, $2
; MIPS2-O0-NEXT:    move $5, $3
; MIPS2-O0-NEXT:    move $6, $18
; MIPS2-O0-NEXT:    move $7, $17
; MIPS2-O0-NEXT:    jalr $25
; MIPS2-O0-NEXT:    nop
; MIPS2-O0-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; MIPS2-O0-NEXT:    lw $17, 20($sp) # 4-byte Folded Reload
; MIPS2-O0-NEXT:    lw $18, 24($sp) # 4-byte Folded Reload
; MIPS2-O0-NEXT:    lw $ra, 28($sp) # 4-byte Folded Reload
; MIPS2-O0-NEXT:    addiu $sp, $sp, 32
; MIPS2-O0-NEXT:    jr $ra
; MIPS2-O0-NEXT:    nop
;
; MIPS32-O0-LABEL: srem_i64:
; MIPS32-O0:       # %bb.0: # %entry
; MIPS32-O0-NEXT:    lui $2, %hi(_gp_disp)
; MIPS32-O0-NEXT:    addiu $2, $2, %lo(_gp_disp)
; MIPS32-O0-NEXT:    addiu $sp, $sp, -32
; MIPS32-O0-NEXT:    .cfi_def_cfa_offset 32
; MIPS32-O0-NEXT:    sw $ra, 28($sp) # 4-byte Folded Spill
; MIPS32-O0-NEXT:    sw $18, 24($sp) # 4-byte Folded Spill
; MIPS32-O0-NEXT:    sw $17, 20($sp) # 4-byte Folded Spill
; MIPS32-O0-NEXT:    sw $16, 16($sp) # 4-byte Folded Spill
; MIPS32-O0-NEXT:    .cfi_offset 31, -4
; MIPS32-O0-NEXT:    .cfi_offset 18, -8
; MIPS32-O0-NEXT:    .cfi_offset 17, -12
; MIPS32-O0-NEXT:    .cfi_offset 16, -16
; MIPS32-O0-NEXT:    addu $16, $2, $25
; MIPS32-O0-NEXT:    lw $17, 52($sp)
; MIPS32-O0-NEXT:    lw $18, 48($sp)
; MIPS32-O0-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS32-O0-NEXT:    move $gp, $16
; MIPS32-O0-NEXT:    jalr $25
; MIPS32-O0-NEXT:    nop
; MIPS32-O0-NEXT:    lw $25, %call16(__moddi3)($16)
; MIPS32-O0-NEXT:    move $4, $2
; MIPS32-O0-NEXT:    move $5, $3
; MIPS32-O0-NEXT:    move $6, $18
; MIPS32-O0-NEXT:    move $7, $17
; MIPS32-O0-NEXT:    jalr $25
; MIPS32-O0-NEXT:    nop
; MIPS32-O0-NEXT:    lw $16, 16($sp) # 4-byte Folded Reload
; MIPS32-O0-NEXT:    lw $17, 20($sp) # 4-byte Folded Reload
; MIPS32-O0-NEXT:    lw $18, 24($sp) # 4-byte Folded Reload
; MIPS32-O0-NEXT:    lw $ra, 28($sp) # 4-byte Folded Reload
; MIPS32-O0-NEXT:    addiu $sp, $sp, 32
; MIPS32-O0-NEXT:    jr $ra
; MIPS32-O0-NEXT:    nop
entry:
  %rem = srem i64 %a, %b
  %rem1 = srem i64 %rem, %c
  ret i64 %rem1
}

define signext i32 @srem_lw_srem_i32(i32 signext %a, i32 signext %b, i32 signext %c) {
; MIPS2-LABEL: srem_lw_srem_i32:
; MIPS2:       # %bb.0: # %entry
; MIPS2-NEXT:    addiu $sp, $sp, -16
; MIPS2-NEXT:    .cfi_def_cfa_offset 16
; MIPS2-NEXT:    div $zero, $4, $5
; MIPS2-NEXT:    teq $5, $zero, 7
; MIPS2-NEXT:    mfhi $1
; MIPS2-NEXT:    nop
; MIPS2-NEXT:    nop
; MIPS2-NEXT:    div $zero, $1, $6
; MIPS2-NEXT:    teq $6, $zero, 7
; MIPS2-NEXT:    mfhi $2
; MIPS2-NEXT:    sw $5, 8($sp)
; MIPS2-NEXT:    sw $4, 12($sp)
; MIPS2-NEXT:    sw $6, 4($sp)
; MIPS2-NEXT:    jr $ra
; MIPS2-NEXT:    addiu $sp, $sp, 16
;
; MIPS32-LABEL: srem_lw_srem_i32:
; MIPS32:       # %bb.0: # %entry
; MIPS32-NEXT:    addiu $sp, $sp, -16
; MIPS32-NEXT:    .cfi_def_cfa_offset 16
; MIPS32-NEXT:    div $zero, $4, $5
; MIPS32-NEXT:    teq $5, $zero, 7
; MIPS32-NEXT:    mfhi $1
; MIPS32-NEXT:    div $zero, $1, $6
; MIPS32-NEXT:    teq $6, $zero, 7
; MIPS32-NEXT:    mfhi $2
; MIPS32-NEXT:    sw $5, 8($sp)
; MIPS32-NEXT:    sw $4, 12($sp)
; MIPS32-NEXT:    sw $6, 4($sp)
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    addiu $sp, $sp, 16
;
; MIPS3-LABEL: srem_lw_srem_i32:
; MIPS3:       # %bb.0: # %entry
; MIPS3-NEXT:    daddiu $sp, $sp, -16
; MIPS3-NEXT:    .cfi_def_cfa_offset 16
; MIPS3-NEXT:    div $zero, $4, $5
; MIPS3-NEXT:    teq $5, $zero, 7
; MIPS3-NEXT:    mfhi $1
; MIPS3-NEXT:    nop
; MIPS3-NEXT:    nop
; MIPS3-NEXT:    div $zero, $1, $6
; MIPS3-NEXT:    teq $6, $zero, 7
; MIPS3-NEXT:    mfhi $2
; MIPS3-NEXT:    sw $5, 8($sp)
; MIPS3-NEXT:    sw $4, 12($sp)
; MIPS3-NEXT:    sw $6, 4($sp)
; MIPS3-NEXT:    jr $ra
; MIPS3-NEXT:    daddiu $sp, $sp, 16
;
; MIPS64-LABEL: srem_lw_srem_i32:
; MIPS64:       # %bb.0: # %entry
; MIPS64-NEXT:    daddiu $sp, $sp, -16
; MIPS64-NEXT:    .cfi_def_cfa_offset 16
; MIPS64-NEXT:    div $zero, $4, $5
; MIPS64-NEXT:    teq $5, $zero, 7
; MIPS64-NEXT:    mfhi $1
; MIPS64-NEXT:    div $zero, $1, $6
; MIPS64-NEXT:    teq $6, $zero, 7
; MIPS64-NEXT:    mfhi $2
; MIPS64-NEXT:    sw $5, 8($sp)
; MIPS64-NEXT:    sw $4, 12($sp)
; MIPS64-NEXT:    sw $6, 4($sp)
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    daddiu $sp, $sp, 16
;
; MIPS2-O0-LABEL: srem_lw_srem_i32:
; MIPS2-O0:       # %bb.0: # %entry
; MIPS2-O0-NEXT:    addiu $sp, $sp, -16
; MIPS2-O0-NEXT:    .cfi_def_cfa_offset 16
; MIPS2-O0-NEXT:    sw $4, 12($sp)
; MIPS2-O0-NEXT:    sw $5, 8($sp)
; MIPS2-O0-NEXT:    sw $6, 4($sp)
; MIPS2-O0-NEXT:    lw $1, 12($sp)
; MIPS2-O0-NEXT:    lw $2, 8($sp)
; MIPS2-O0-NEXT:    div $zero, $1, $2
; MIPS2-O0-NEXT:    teq $2, $zero, 7
; MIPS2-O0-NEXT:    mfhi $1
; MIPS2-O0-NEXT:    lw $2, 4($sp)
; MIPS2-O0-NEXT:    nop
; MIPS2-O0-NEXT:    div $zero, $1, $2
; MIPS2-O0-NEXT:    teq $2, $zero, 7
; MIPS2-O0-NEXT:    mfhi $2
; MIPS2-O0-NEXT:    addiu $sp, $sp, 16
; MIPS2-O0-NEXT:    jr $ra
; MIPS2-O0-NEXT:    nop
;
; MIPS32-O0-LABEL: srem_lw_srem_i32:
; MIPS32-O0:       # %bb.0: # %entry
; MIPS32-O0-NEXT:    addiu $sp, $sp, -16
; MIPS32-O0-NEXT:    .cfi_def_cfa_offset 16
; MIPS32-O0-NEXT:    sw $4, 12($sp)
; MIPS32-O0-NEXT:    sw $5, 8($sp)
; MIPS32-O0-NEXT:    sw $6, 4($sp)
; MIPS32-O0-NEXT:    lw $1, 12($sp)
; MIPS32-O0-NEXT:    lw $2, 8($sp)
; MIPS32-O0-NEXT:    div $zero, $1, $2
; MIPS32-O0-NEXT:    teq $2, $zero, 7
; MIPS32-O0-NEXT:    mfhi $1
; MIPS32-O0-NEXT:    lw $2, 4($sp)
; MIPS32-O0-NEXT:    div $zero, $1, $2
; MIPS32-O0-NEXT:    teq $2, $zero, 7
; MIPS32-O0-NEXT:    mfhi $2
; MIPS32-O0-NEXT:    addiu $sp, $sp, 16
; MIPS32-O0-NEXT:    jr $ra
; MIPS32-O0-NEXT:    nop
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  %c.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  store i32 %c, ptr %c.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %rem = srem i32 %0, %1
  %2 = load i32, ptr %c.addr, align 4
  %rem1 = srem i32 %rem, %2
  ret i32 %rem1
}

