; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=amdgpu9.00-amd-amdhsa -O0 < %s | FileCheck -check-prefix=GFX900 %s
; RUN: llc -mtriple=amdgpu9.06-amd-amdhsa -O0 < %s | FileCheck -check-prefix=GFX906 %s
; RUN: llc -mtriple=amdgpu9.08-amd-amdhsa -O0 < %s | FileCheck -check-prefix=GFX908 %s
; RUN: llc -mtriple=amdgpu9.0a-amd-amdhsa -O0 < %s | FileCheck -check-prefix=GFX90a %s

; This test used to crash for gfx908 while allocating the tuple. Compared to the other subtargets,
; gfx908 marks an extra VGPR reserved for AGPR to VGPR copy that puts more register pressure.
; To minimize the register pressure, the VGPRs used for CSR SGPR spilling has been picked from the
; higher available range there by allowing more VGPRs available in the lowest range for allocation.

define i32 @test_tuple(<16 x i64> %0) {
; GFX900-LABEL: test_tuple:
; GFX900:       ; %bb.0:
; GFX900-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX900-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX900-NEXT:    ; kill: def $vgpr30 killed $vgpr30 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr29 killed $vgpr29 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr28 killed $vgpr28 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr27 killed $vgpr27 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr26 killed $vgpr26 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr25 killed $vgpr25 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr24 killed $vgpr24 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr23 killed $vgpr23 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr22 killed $vgpr22 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr21 killed $vgpr21 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr20 killed $vgpr20 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr19 killed $vgpr19 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr18 killed $vgpr18 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr17 killed $vgpr17 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr16 killed $vgpr16 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr15 killed $vgpr15 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr14 killed $vgpr14 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr13 killed $vgpr13 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr12 killed $vgpr12 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr11 killed $vgpr11 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr10 killed $vgpr10 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr9 killed $vgpr9 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr8 killed $vgpr8 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr7 killed $vgpr7 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr6 killed $vgpr6 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr5 killed $vgpr5 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr4 killed $vgpr4 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr2 killed $vgpr2 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr1 killed $vgpr1 killed $exec
; GFX900-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX900-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; GFX900-NEXT:    s_waitcnt vmcnt(0)
; GFX900-NEXT:    v_mov_b32_e32 v31, v0
; GFX900-NEXT:    v_mov_b32_e32 v32, v1
; GFX900-NEXT:    v_mov_b32_e32 v33, v2
; GFX900-NEXT:    v_mov_b32_e32 v34, v3
; GFX900-NEXT:    v_mov_b32_e32 v35, v4
; GFX900-NEXT:    v_mov_b32_e32 v36, v5
; GFX900-NEXT:    v_mov_b32_e32 v37, v6
; GFX900-NEXT:    v_mov_b32_e32 v38, v7
; GFX900-NEXT:    v_mov_b32_e32 v39, v8
; GFX900-NEXT:    v_mov_b32_e32 v40, v9
; GFX900-NEXT:    v_mov_b32_e32 v41, v10
; GFX900-NEXT:    v_mov_b32_e32 v42, v11
; GFX900-NEXT:    v_mov_b32_e32 v43, v12
; GFX900-NEXT:    v_mov_b32_e32 v44, v13
; GFX900-NEXT:    v_mov_b32_e32 v45, v14
; GFX900-NEXT:    v_mov_b32_e32 v46, v15
; GFX900-NEXT:    v_mov_b32_e32 v47, v16
; GFX900-NEXT:    v_mov_b32_e32 v48, v17
; GFX900-NEXT:    v_mov_b32_e32 v49, v18
; GFX900-NEXT:    v_mov_b32_e32 v50, v19
; GFX900-NEXT:    v_mov_b32_e32 v51, v20
; GFX900-NEXT:    v_mov_b32_e32 v52, v21
; GFX900-NEXT:    v_mov_b32_e32 v53, v22
; GFX900-NEXT:    v_mov_b32_e32 v54, v23
; GFX900-NEXT:    v_mov_b32_e32 v55, v24
; GFX900-NEXT:    v_mov_b32_e32 v56, v25
; GFX900-NEXT:    v_mov_b32_e32 v57, v26
; GFX900-NEXT:    v_mov_b32_e32 v58, v27
; GFX900-NEXT:    v_mov_b32_e32 v59, v28
; GFX900-NEXT:    v_mov_b32_e32 v60, v29
; GFX900-NEXT:    ; kill: def $vgpr61 killed $vgpr30 killed $exec
; GFX900-NEXT:    v_mov_b32_e32 v0, 0
; GFX900-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX900-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX900-NEXT:    s_waitcnt vmcnt(0)
; GFX900-NEXT:    s_setpc_b64 s[30:31]
;
; GFX906-LABEL: test_tuple:
; GFX906:       ; %bb.0:
; GFX906-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX906-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX906-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX906-NEXT:    ; kill: def $vgpr30 killed $vgpr30 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr29 killed $vgpr29 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr28 killed $vgpr28 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr27 killed $vgpr27 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr26 killed $vgpr26 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr25 killed $vgpr25 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr24 killed $vgpr24 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr23 killed $vgpr23 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr22 killed $vgpr22 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr21 killed $vgpr21 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr20 killed $vgpr20 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr19 killed $vgpr19 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr18 killed $vgpr18 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr17 killed $vgpr17 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr16 killed $vgpr16 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr15 killed $vgpr15 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr14 killed $vgpr14 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr13 killed $vgpr13 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr12 killed $vgpr12 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr11 killed $vgpr11 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr10 killed $vgpr10 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr9 killed $vgpr9 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr8 killed $vgpr8 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr7 killed $vgpr7 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr6 killed $vgpr6 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr5 killed $vgpr5 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr4 killed $vgpr4 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr2 killed $vgpr2 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr1 killed $vgpr1 killed $exec
; GFX906-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX906-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; GFX906-NEXT:    s_waitcnt vmcnt(0)
; GFX906-NEXT:    v_mov_b32_e32 v31, v0
; GFX906-NEXT:    v_mov_b32_e32 v32, v1
; GFX906-NEXT:    v_mov_b32_e32 v33, v2
; GFX906-NEXT:    v_mov_b32_e32 v34, v3
; GFX906-NEXT:    v_mov_b32_e32 v35, v4
; GFX906-NEXT:    v_mov_b32_e32 v36, v5
; GFX906-NEXT:    v_mov_b32_e32 v37, v6
; GFX906-NEXT:    v_mov_b32_e32 v38, v7
; GFX906-NEXT:    v_mov_b32_e32 v39, v8
; GFX906-NEXT:    v_mov_b32_e32 v40, v9
; GFX906-NEXT:    v_mov_b32_e32 v41, v10
; GFX906-NEXT:    v_mov_b32_e32 v42, v11
; GFX906-NEXT:    v_mov_b32_e32 v43, v12
; GFX906-NEXT:    v_mov_b32_e32 v44, v13
; GFX906-NEXT:    v_mov_b32_e32 v45, v14
; GFX906-NEXT:    v_mov_b32_e32 v46, v15
; GFX906-NEXT:    v_mov_b32_e32 v47, v16
; GFX906-NEXT:    v_mov_b32_e32 v48, v17
; GFX906-NEXT:    v_mov_b32_e32 v49, v18
; GFX906-NEXT:    v_mov_b32_e32 v50, v19
; GFX906-NEXT:    v_mov_b32_e32 v51, v20
; GFX906-NEXT:    v_mov_b32_e32 v52, v21
; GFX906-NEXT:    v_mov_b32_e32 v53, v22
; GFX906-NEXT:    v_mov_b32_e32 v54, v23
; GFX906-NEXT:    v_mov_b32_e32 v55, v24
; GFX906-NEXT:    v_mov_b32_e32 v56, v25
; GFX906-NEXT:    v_mov_b32_e32 v57, v26
; GFX906-NEXT:    v_mov_b32_e32 v58, v27
; GFX906-NEXT:    v_mov_b32_e32 v59, v28
; GFX906-NEXT:    v_mov_b32_e32 v60, v29
; GFX906-NEXT:    ; kill: def $vgpr61 killed $vgpr30 killed $exec
; GFX906-NEXT:    v_mov_b32_e32 v0, 0
; GFX906-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX906-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX906-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX906-NEXT:    s_waitcnt vmcnt(0)
; GFX906-NEXT:    s_setpc_b64 s[30:31]
;
; GFX908-LABEL: test_tuple:
; GFX908:       ; %bb.0:
; GFX908-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX908-NEXT:    v_accvgpr_write_b32 a0, v40 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a1, v41 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a2, v42 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a3, v43 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a4, v44 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a5, v45 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a6, v46 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a7, v47 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a8, v56 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a9, v57 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a10, v58 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a11, v59 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a12, v60 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a13, v61 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_write_b32 a14, v62 ; Reload Reuse
; GFX908-NEXT:    ; kill: def $vgpr30 killed $vgpr30 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr29 killed $vgpr29 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr28 killed $vgpr28 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr27 killed $vgpr27 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr26 killed $vgpr26 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr25 killed $vgpr25 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr24 killed $vgpr24 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr23 killed $vgpr23 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr22 killed $vgpr22 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr21 killed $vgpr21 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr20 killed $vgpr20 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr19 killed $vgpr19 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr18 killed $vgpr18 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr17 killed $vgpr17 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr16 killed $vgpr16 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr15 killed $vgpr15 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr14 killed $vgpr14 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr13 killed $vgpr13 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr12 killed $vgpr12 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr11 killed $vgpr11 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr10 killed $vgpr10 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr9 killed $vgpr9 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr8 killed $vgpr8 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr7 killed $vgpr7 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr6 killed $vgpr6 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr5 killed $vgpr5 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr4 killed $vgpr4 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr2 killed $vgpr2 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr1 killed $vgpr1 killed $exec
; GFX908-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX908-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; GFX908-NEXT:    s_waitcnt vmcnt(0)
; GFX908-NEXT:    v_mov_b32_e32 v31, v0
; GFX908-NEXT:    v_mov_b32_e32 v32, v1
; GFX908-NEXT:    v_mov_b32_e32 v33, v2
; GFX908-NEXT:    v_mov_b32_e32 v34, v3
; GFX908-NEXT:    v_mov_b32_e32 v35, v4
; GFX908-NEXT:    v_mov_b32_e32 v36, v5
; GFX908-NEXT:    v_mov_b32_e32 v37, v6
; GFX908-NEXT:    v_mov_b32_e32 v38, v7
; GFX908-NEXT:    v_mov_b32_e32 v39, v8
; GFX908-NEXT:    v_mov_b32_e32 v40, v9
; GFX908-NEXT:    v_mov_b32_e32 v41, v10
; GFX908-NEXT:    v_mov_b32_e32 v42, v11
; GFX908-NEXT:    v_mov_b32_e32 v43, v12
; GFX908-NEXT:    v_mov_b32_e32 v44, v13
; GFX908-NEXT:    v_mov_b32_e32 v45, v14
; GFX908-NEXT:    v_mov_b32_e32 v46, v15
; GFX908-NEXT:    v_mov_b32_e32 v47, v16
; GFX908-NEXT:    v_mov_b32_e32 v48, v17
; GFX908-NEXT:    v_mov_b32_e32 v49, v18
; GFX908-NEXT:    v_mov_b32_e32 v50, v19
; GFX908-NEXT:    v_mov_b32_e32 v51, v20
; GFX908-NEXT:    v_mov_b32_e32 v52, v21
; GFX908-NEXT:    v_mov_b32_e32 v53, v22
; GFX908-NEXT:    v_mov_b32_e32 v54, v23
; GFX908-NEXT:    v_mov_b32_e32 v55, v24
; GFX908-NEXT:    v_mov_b32_e32 v56, v25
; GFX908-NEXT:    v_mov_b32_e32 v57, v26
; GFX908-NEXT:    v_mov_b32_e32 v58, v27
; GFX908-NEXT:    v_mov_b32_e32 v59, v28
; GFX908-NEXT:    v_mov_b32_e32 v60, v29
; GFX908-NEXT:    ; kill: def $vgpr61 killed $vgpr30 killed $exec
; GFX908-NEXT:    v_mov_b32_e32 v0, 0
; GFX908-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX908-NEXT:    v_accvgpr_read_b32 v62, a14 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v61, a13 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v60, a12 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v59, a11 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v58, a10 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v57, a9 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v56, a8 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v47, a7 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v46, a6 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v45, a5 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v44, a4 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v43, a3 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v42, a2 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v41, a1 ; Reload Reuse
; GFX908-NEXT:    v_accvgpr_read_b32 v40, a0 ; Reload Reuse
; GFX908-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90a-LABEL: test_tuple:
; GFX90a:       ; %bb.0:
; GFX90a-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90a-NEXT:    v_accvgpr_write_b32 a0, v40 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a1, v41 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a2, v42 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a3, v43 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a4, v44 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a5, v45 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a6, v46 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a7, v47 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a8, v56 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a9, v57 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a10, v58 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a11, v59 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a12, v60 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a13, v61 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a14, v62 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_write_b32 a15, v63 ; Reload Reuse
; GFX90a-NEXT:    ; kill: def $vgpr30 killed $vgpr30 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr29 killed $vgpr29 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr28 killed $vgpr28 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr27 killed $vgpr27 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr26 killed $vgpr26 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr25 killed $vgpr25 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr24 killed $vgpr24 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr23 killed $vgpr23 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr22 killed $vgpr22 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr21 killed $vgpr21 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr20 killed $vgpr20 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr19 killed $vgpr19 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr18 killed $vgpr18 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr17 killed $vgpr17 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr16 killed $vgpr16 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr15 killed $vgpr15 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr14 killed $vgpr14 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr13 killed $vgpr13 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr12 killed $vgpr12 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr11 killed $vgpr11 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr10 killed $vgpr10 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr9 killed $vgpr9 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr8 killed $vgpr8 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr7 killed $vgpr7 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr6 killed $vgpr6 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr5 killed $vgpr5 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr4 killed $vgpr4 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr3 killed $vgpr3 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr2 killed $vgpr2 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr1 killed $vgpr1 killed $exec
; GFX90a-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX90a-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; GFX90a-NEXT:    v_mov_b32_e32 v32, v0
; GFX90a-NEXT:    v_mov_b32_e32 v33, v1
; GFX90a-NEXT:    v_mov_b32_e32 v34, v2
; GFX90a-NEXT:    v_mov_b32_e32 v35, v3
; GFX90a-NEXT:    v_mov_b32_e32 v36, v4
; GFX90a-NEXT:    v_mov_b32_e32 v37, v5
; GFX90a-NEXT:    v_mov_b32_e32 v38, v6
; GFX90a-NEXT:    v_mov_b32_e32 v39, v7
; GFX90a-NEXT:    v_mov_b32_e32 v40, v8
; GFX90a-NEXT:    v_mov_b32_e32 v41, v9
; GFX90a-NEXT:    v_mov_b32_e32 v42, v10
; GFX90a-NEXT:    v_mov_b32_e32 v43, v11
; GFX90a-NEXT:    v_mov_b32_e32 v44, v12
; GFX90a-NEXT:    v_mov_b32_e32 v45, v13
; GFX90a-NEXT:    v_mov_b32_e32 v46, v14
; GFX90a-NEXT:    v_mov_b32_e32 v47, v15
; GFX90a-NEXT:    v_mov_b32_e32 v48, v16
; GFX90a-NEXT:    v_mov_b32_e32 v49, v17
; GFX90a-NEXT:    v_mov_b32_e32 v50, v18
; GFX90a-NEXT:    v_mov_b32_e32 v51, v19
; GFX90a-NEXT:    v_mov_b32_e32 v52, v20
; GFX90a-NEXT:    v_mov_b32_e32 v53, v21
; GFX90a-NEXT:    v_mov_b32_e32 v54, v22
; GFX90a-NEXT:    v_mov_b32_e32 v55, v23
; GFX90a-NEXT:    v_mov_b32_e32 v56, v24
; GFX90a-NEXT:    v_mov_b32_e32 v57, v25
; GFX90a-NEXT:    v_mov_b32_e32 v58, v26
; GFX90a-NEXT:    v_mov_b32_e32 v59, v27
; GFX90a-NEXT:    v_mov_b32_e32 v60, v28
; GFX90a-NEXT:    v_mov_b32_e32 v61, v29
; GFX90a-NEXT:    ; kill: def $vgpr62 killed $vgpr30 killed $exec
; GFX90a-NEXT:    v_mov_b32_e32 v0, 0
; GFX90a-NEXT:    ; kill: def $vgpr0 killed $vgpr0 killed $exec
; GFX90a-NEXT:    v_accvgpr_read_b32 v63, a15 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v62, a14 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v61, a13 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v60, a12 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v59, a11 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v58, a10 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v57, a9 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v56, a8 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v47, a7 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v46, a6 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v45, a5 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v44, a4 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v43, a3 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v42, a2 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v41, a1 ; Reload Reuse
; GFX90a-NEXT:    v_accvgpr_read_b32 v40, a0 ; Reload Reuse
; GFX90a-NEXT:    s_waitcnt vmcnt(0)
; GFX90a-NEXT:    s_setpc_b64 s[30:31]
  %2 = shufflevector <16 x i64> %0, <16 x i64> zeroinitializer, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret i32 0
}
