; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv8-unknown-linux-unknown -mattr=-fp16 -O0 < %s | FileCheck %s

declare fastcc half @getConstant()

declare fastcc i1 @isEqual(half %0, half %1)

define internal fastcc void @main() {
; CHECK-LABEL: main:
; CHECK:       @ %bb.0: @ %Entry
; CHECK-NEXT:    push {r11, lr}
; CHECK-NEXT:    mov r11, sp
; CHECK-NEXT:    vpush {d8}
; CHECK-NEXT:    sub sp, sp, #8
; CHECK-NEXT:    mov r0, #31744
; CHECK-NEXT:    strh r0, [sp, #6]
; CHECK-NEXT:    ldrh r0, [sp, #6]
; CHECK-NEXT:    vmov s16, r0
; CHECK-NEXT:    bl getConstant
; CHECK-NEXT:    vmov.f32 s1, s0
; CHECK-NEXT:    vmov.f32 s0, s16
; CHECK-NEXT:    bl isEqual
; CHECK-NEXT:    sub sp, r11, #8
; CHECK-NEXT:    vpop {d8}
; CHECK-NEXT:    pop {r11, pc}
Entry:
    ; First arg directly from constant
    %const = alloca half, align 2
    store half 0xH7C00, ptr %const, align 2
    %arg1 = load half, ptr %const, align 2
    ; Second arg from fucntion return
    %arg2 = call fastcc half @getConstant()
    ; Arguments should have equivalent mangling
    %result = call fastcc i1 @isEqual(half %arg1, half %arg2)
    ret void
}
