; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -mtriple=aarch64-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s

define void @test() nounwind {
; CHECK-LABEL: test:
; CHECK:       // %bb.0:
; CHECK-NEXT:    stp x30, x19, [sp, #-16]! // 16-byte Folded Spill
; CHECK-NEXT:    mov x19, xzr
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    mov x1, x19
; CHECK-NEXT:    bl returns_arg
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    mov x1, x19
; CHECK-NEXT:    bl accepts_arg
; CHECK-NEXT:    ldp x30, x19, [sp], #16 // 16-byte Folded Reload
; CHECK-NEXT:    ret
  %x = call i128 @returns_arg(i128 0)
  call void @accepts_arg(i128 %x)
  ret void
}

declare i128 @returns_arg(i128 returned)
declare void @accepts_arg(i128)
