; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --no_x86_scrub_sp --version 4
; RUN: llc -O0 -mtriple=x86_64 -verify-machineinstrs < %s | FileCheck %s --check-prefix=CHECK
%large = type [4294967295 x i8]

define void @foo() unnamed_addr #0 {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $8589934472, %rax # imm = 0x1FFFFFF88
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 8589934480
; CHECK-NEXT:    movabsq $4294967177, %rax # imm = 0xFFFFFF89
; CHECK-NEXT:    movb $42, (%rsp,%rax)
; CHECK-NEXT:    movb $43, -118(%rsp)
; CHECK-NEXT:    movabsq $8589934472, %rax # imm = 0x1FFFFFF88
; CHECK-NEXT:    addq %rax, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %large1 = alloca %large, align 1
  %large2 = alloca %large, align 1
  %ptrLarge1 = getelementptr inbounds %large, ptr %large1, i64 0, i64 0
  store i8 42, ptr %ptrLarge1, align 1
  %ptrLarge2 = getelementptr inbounds %large, ptr %large2, i64 0, i64 0
  store i8 43, ptr %ptrLarge2, align 1
  ret void
}

declare ptr @baz(ptr, ptr, ptr, ptr)

define ptr @scavenge_spill() unnamed_addr #0 {
; CHECK-LABEL: scavenge_spill:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    movabsq $25769803784, %rax # imm = 0x600000008
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 25769803824
; CHECK-NEXT:    .cfi_offset %rbx, -40
; CHECK-NEXT:    .cfi_offset %r12, -32
; CHECK-NEXT:    .cfi_offset %r14, -24
; CHECK-NEXT:    .cfi_offset %r15, -16
; CHECK-NEXT:    movabsq $21474836489, %rax # imm = 0x500000009
; CHECK-NEXT:    leaq (%rsp,%rax), %rdi
; CHECK-NEXT:    movabsq $17179869194, %rax # imm = 0x40000000A
; CHECK-NEXT:    leaq (%rsp,%rax), %rbx
; CHECK-NEXT:    movabsq $12884901899, %rax # imm = 0x30000000B
; CHECK-NEXT:    leaq (%rsp,%rax), %r14
; CHECK-NEXT:    movabsq $8589934604, %rax # imm = 0x20000000C
; CHECK-NEXT:    leaq (%rsp,%rax), %r15
; CHECK-NEXT:    movq %rbx, %rsi
; CHECK-NEXT:    movq %r14, %rdx
; CHECK-NEXT:    movq %r15, %rcx
; CHECK-NEXT:    callq baz@PLT
; CHECK-NEXT:    movq %rax, %r12
; CHECK-NEXT:    leaq 14(%rsp), %rdi
; CHECK-NEXT:    movq %rbx, %rsi
; CHECK-NEXT:    movq %r14, %rdx
; CHECK-NEXT:    movq %r15, %rcx
; CHECK-NEXT:    callq baz@PLT
; CHECK-NEXT:    movq %r12, %rax
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    movabsq $25769803792, %rax # imm = 0x600000010
; CHECK-NEXT:    addq %rsp, %rax
; CHECK-NEXT:    xchgq %rax, (%rsp)
; CHECK-NEXT:    movq (%rsp), %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %large1 = alloca %large, align 1
  %ptrLarge1 = getelementptr inbounds %large, ptr %large1, i64 0, i64 0
  %large2 = alloca %large, align 1
  %ptrLarge2 = getelementptr inbounds %large, ptr %large2, i64 0, i64 0
  %large3 = alloca %large, align 1
  %ptrLarge3 = getelementptr inbounds %large, ptr %large3, i64 0, i64 0
  %large4 = alloca %large, align 1
  %ptrLarge4 = getelementptr inbounds %large, ptr %large4, i64 0, i64 0
  %large5 = alloca %large, align 1
  %ptrLarge5 = getelementptr inbounds %large, ptr %large5, i64 0, i64 0
  %ret1 = call ptr @baz(ptr %ptrLarge1, ptr %ptrLarge2, ptr %ptrLarge3, ptr %ptrLarge4)
  %large6 = alloca %large, align 1
  %ptrLarge6 = getelementptr inbounds %large, ptr %large6, i64 0, i64 0
  %ret2 = call ptr @baz(ptr %ptrLarge6, ptr %ptrLarge2, ptr %ptrLarge3, ptr %ptrLarge4)
  ret ptr %ret1
}
